// Copyright 2026 Ricardo Escalon
// SPDX-License-Identifier: GPL-2.0+

#ifndef USER_TAP_DANCE_H
#define USER_TAP_DANCE_H

// Keep this header preprocessor-only because layout.h is included from config.h.
#define TD_TAB_ESC_CLOSE 0
#define TD_LEFT_BRACKET 1
#define TD_RIGHT_BRACKET 2
#define TD_SLASH_PIPE 3
#define TD_PLUS_EQUAL 4
#define TD_NUM_TWO_COMMA_LT 5
#define TD_NUM_THREE_DOT_GT 6
#define TD_NAV_UP 7
#define TD_NAV_LEFT 8
#define TD_NAV_DOWN 9
#define TD_NAV_RIGHT 10
#define TD_BASE_GUI_SNAP 11
#define TD_NUM_GUI_NAV_SNAP 12
#define TD_SYM_GUI_EXT_SNAP 13
#define TD_SYS_GUI_MED_SNAP 14
#define TD_SPANISH_LEFT 15
#define TD_SPANISH_RIGHT 16
#define TD_CAPS_LONG 17
#define TD_MS_STYLE_UP 18
#define TD_MS_STYLE_LEFT 19
#define TD_MS_STYLE_DOWN 20
#define TD_MS_STYLE_RIGHT 21

#define SPANISH_SOURCE_NONE 0
#define SPANISH_SOURCE_LEFT 1
#define SPANISH_SOURCE_RIGHT 2

#define TAB_ESC_CLOSE TD(TD_TAB_ESC_CLOSE)
#define LEFT_BRACKET TD(TD_LEFT_BRACKET)
#define RIGHT_BRACKET TD(TD_RIGHT_BRACKET)
#define SLASH_PIPE TD(TD_SLASH_PIPE)
#define PLUS_EQUAL TD(TD_PLUS_EQUAL)
#define NUM_TWO_COMMA_LT TD(TD_NUM_TWO_COMMA_LT)
#define NUM_THREE_DOT_GT TD(TD_NUM_THREE_DOT_GT)
#define NAV_UP_DANCE TD(TD_NAV_UP)
#define NAV_LEFT_DANCE TD(TD_NAV_LEFT)
#define NAV_DOWN_DANCE TD(TD_NAV_DOWN)
#define NAV_RIGHT_DANCE TD(TD_NAV_RIGHT)
#define BASE_GUI_SNAP TD(TD_BASE_GUI_SNAP)
#define NUM_GUI_NAV_SNAP TD(TD_NUM_GUI_NAV_SNAP)
#define SYM_GUI_EXT_SNAP TD(TD_SYM_GUI_EXT_SNAP)
#define SYS_GUI_MED_SNAP TD(TD_SYS_GUI_MED_SNAP)
#define SPANISH_LEFT_DANCE TD(TD_SPANISH_LEFT)
#define SPANISH_RIGHT_DANCE TD(TD_SPANISH_RIGHT)
#define CAPS_LONG_DANCE TD(TD_CAPS_LONG)
#define MS_STYLE_UP_DANCE TD(TD_MS_STYLE_UP)
#define MS_STYLE_LEFT_DANCE TD(TD_MS_STYLE_LEFT)
#define MS_STYLE_DOWN_DANCE TD(TD_MS_STYLE_DOWN)
#define MS_STYLE_RIGHT_DANCE TD(TD_MS_STYLE_RIGHT)

#endif
