name: Build CRKBD firmware
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
#    container: qmkfm/qmk_cli
    container: qmkfm/base_container
    strategy:
      fail-fast: false
      matrix:
        keyboard:
        - corne
        keymap:
        - ${{ github.actor }}
        side:
        - LEFT
        - RIGHT

    steps:

    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: develop
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ matrix.keymap }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build crkbd
      run: qmk compile -e OLED=${{ matrix.side }}CAT "users/${{ matrix.keymap }}/keymaps/${{ matrix.keyboard }}.json"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.keyboard }}_${{ matrix.side }}_${{ matrix.keymap }}
        retention-days: 2
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
