name: Build QMK Userspace
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Userspace
    runs-on: ubuntu-latest
    container: qmkfm/base_container
    strategy:
      fail-fast: false
      matrix:
        keyboard:
        - 3w6
        - cradio
        - macro3
        - mark65
        - technik
        include:
        - keyboard: corne
          oled: LEFTCAT
        - keyboard: corne
          oled: RIGHTCAT
        - keyboard: corne
          oled: LUNA

    steps:

    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: recursive
        persist-credentials: false

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Build firmware
      id: build
      shell: bash
      run: |
        if [ ${{ matrix.keyboard }} == "corne" ]
        then
          qmk compile -j 10 -e OLED=${{ matrix.oled }} users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json
          OUTPUT=${{ matrix.keyboard }}_${{ matrix.oled }}
        else
          qmk compile -j 10 users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json
          OUTPUT=${{ matrix.keyboard }}
        fi
        echo "::set-output name=artifact-name::${OUTPUT}"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build.outputs.artifact-name }}
        retention-days: 2
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

  prune:
    name: Prune
    needs: build
    uses: filterpaper/blocklists/.github/workflows/delete_workflow.yml@main
    with:
      days: 7
