name: Build QMK userspace
on: [workflow_dispatch]

env:
  USERSPACE: ${{ github.actor }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/base_container
    strategy:
      fail-fast: false
      matrix:
        keyboard:
        - 3w6
        - adux
        - cradio
        - macro3
        - mark65
        - technik
        include:
        - keyboard: corne
          oled: LEFTCAT
        - keyboard: corne
          oled: RIGHTCAT

    steps:

    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: develop
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ env.USERSPACE }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build firmware
      id: build
      shell: bash
      run: |
        if [[ ${{ matrix.keyboard }} == "corne" ]]
        then
          qmk compile -e OLED=${{ matrix.oled }} "users/${{ env.USERSPACE }}/keymaps/${{ matrix.keyboard }}.json"
          TARGET=$(echo "${{ matrix.keyboard }}" | sed 's#/#_#g')_${{ matrix.oled }}_${{ env.USERSPACE }}
        else
          qmk compile "users/${{ env.USERSPACE }}/keymaps/${{ matrix.keyboard }}.json"
          TARGET=${{ matrix.keyboard }}_${{ env.USERSPACE }}
        fi
        echo "::set-output name=artifact-name::${TARGET}"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.build.outputs.artifact-name }}
        retention-days: 2
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true
