name: Userspace Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/base_container
    strategy:
      fail-fast: false
      matrix:
        keyboard:
        - 3w6
        - cradio
        - macro3
        - mark65
        - technik
        include:
        - keyboard: corne
          oled: LEFTCAT
        - keyboard: corne
          oled: RIGHTCAT
        - keyboard: corne
          oled: LUNA

    steps:
    - name: Checkout QMK source
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Update python dependencies
      run: /usr/bin/python3 -m pip install -r requirements.txt

    - name: Build firmware
      id: build
      working-directory: users/${{ github.actor }}/keymaps
      env:
        build_option: $([ -n "${{ matrix.oled }}" ] && printf " -e OLED=${{ matrix.oled }}")
        output_suffix: $([ -n "${{ matrix.oled }}" ] && printf "_${{ matrix.oled }}")
      run: |
        set -x
        qmk compile -j3 ${{ env.build_option }} ${{ matrix.keyboard }}.json || true
        echo "::set-output name=artifact-name::${{ matrix.keyboard }}${{ env.output_suffix }}"

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 3
        name: ${{ steps.build.outputs.artifact-name }}
        path: |
          *.hex
          *.bin
          *.uf2

  purge:
    uses: filterpaper/scripts/.github/workflows/delete-workflow.yml@main
