name: Userspace Build
on: [push, workflow_dispatch]

jobs:
  build:
    name: Userspace build
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard: [cradio, corne]
        conv: [kb2040]
        hand: [LEFT, RIGHT]
        include:
        - keyboard: cradio
          conv: ''
        - keyboard: 3w6
        - keyboard: mark65
        - keyboard: technik

    steps:
    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Setup variables
      id: vars
      env:
        conv_suffix: $([ ${{ matrix.conv }} ] && printf "_${{ matrix.conv }}")
        hand_suffix: $([ ${{ matrix.hand }} ] && printf "_${{ matrix.hand }}")
      run: |
        set -x
        echo "::set-output name=build-args:: -e CONVERT_TO=${{ matrix.conv }} -e HAND=${{ matrix.hand }}"
        echo "::set-output name=file-name::${{ matrix.keyboard }}${{ env.conv_suffix }}${{ env.hand_suffix }}"
        echo "::set-output name=archive-name::${{ matrix.keyboard }}${{ env.conv_suffix }}"

    - name: Build
      continue-on-error: true
      working-directory: users/${{ github.actor }}/keymaps
      run: qmk -v compile -j 3 ${{ steps.vars.outputs.build-args }} ${{ matrix.keyboard }}.json

    - name: Rename uf2
      if: ${{ matrix.hand != '' }}
      continue-on-error: true
      run: mv -v *.uf2 ${{ steps.vars.outputs.file-name }}.uf2

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 3
        name: ${{ steps.vars.outputs.archive-name }}
        path: |
          *.hex
          *.bin
          *.uf2

  purge:
    uses: filterpaper/scripts/.github/workflows/delete-workflow.yml@main
