name: Build QMK Userspace
on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Userspace
    runs-on: ubuntu-latest
    container: qmkfm/base_container
    strategy:
      fail-fast: false
      matrix:
        keyboard:
        - 3w6
        - cradio
        - macro3
        - mark65
        - technik
        include:
        - keyboard: corne
          oled: LEFTCAT
        - keyboard: corne
          oled: RIGHTCAT
        - keyboard: corne
          oled: LUNA

    steps:
    - name: Checkout develop branch
      if: ${{ (matrix.keyboard != 'rp-cradio') }}
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        ref: develop
        submodules: recursive

    - name: Checkout RP2040 branch
      if: ${{ (matrix.keyboard == 'rp-cradio') }}
      uses: actions/checkout@v3
      with:
        repository: filterpaper/qmk_firmware
        ref: myrp2040
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Update python dependencies
      run: /usr/bin/python3 -m pip install -r requirements.txt

    - name: Build firmware
      id: build
      shell: bash
      working-directory: users/${{ github.actor }}/keymaps
      run: |
        qmk compile -j 10 $([ ! -z ${{ matrix.oled }} ] && echo "-e OLED=${{ matrix.oled }}") ${{ matrix.keyboard }}.json || true
        OUTPUT=${{ matrix.keyboard }}$([ ! -z ${{ matrix.oled }} ] && echo "_${{ matrix.oled }}") || true
        echo "::set-output name=artifact-name::${OUTPUT}"

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.build.outputs.artifact-name }}
        retention-days: 3
        path: |
          *.hex
          *.bin
          *.uf2
      continue-on-error: true

  purge:
    name: Purge
    needs: build
    uses: filterpaper/scripts/.github/workflows/delete-workflow.yml@main
    with:
      days: 5
