name: Build QMK userspace
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - 3w6
          - adux
          - cradio
          - macro3
    steps:

    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        repository: ${{ github.actor }}/qmk_userspace
        path: users/${{ github.actor }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"

    - name: Upload firmware
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.actor }}_firmware
        path: '*.hex'
        retention-days: 2
