name: Build QMK userspace
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        keyboard:
          - 3w6
          - adux
          - cradio
          - macro3
    steps:

    - name: Checkout QMK
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: develop
        fetch-depth: 1
        persist-credentials: false
        submodules: recursive

    - name: Checkout userspace
      uses: actions/checkout@v2
      with:
        path: users/${{ github.actor }}
        fetch-depth: 1
        persist-credentials: false

    - name: Build firmware
      id: build
      run: |
        qmk compile "users/${{ github.actor }}/keymaps/${{ matrix.keyboard }}.json"
        OUTPUT=$(echo "${{ matrix.keyboard }}" | sed 's#/#_#g')_${{ matrix.keymap }}
        echo "::set-output name=artifact-name::${OUTPUT}"

    - name: Archive firmware
      uses: actions/upload-artifact@v2
      with:
        name: "${{ steps.build.outputs.artifact-name }}_firmware"
        retention-days: 2
        path: |
          *.hex
          *.bin
      continue-on-error: true
