name: Development Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        include:
        - keyboard: cradio
          branch: develop
        - keyboard: cradio
          branch: avr-dev

    steps:
    - name: Checkout ${{ matrix.branch }} branch
      uses: actions/checkout@v3
      with:
        repository: filterpaper/qmk_firmware
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Setup variables
      id: vars
      env:
        branch_suffix: $([ -n "${{ matrix.branch}}" ] && printf "_${{ matrix.branch }}")
        conv_option: $([ -n "${{ matrix.conv }}" ] && printf " -e CONVERT_TO=${{ matrix.conv }}")
        conv_suffix: $([ -n "${{ matrix.conv }}" ] && printf "_${{ matrix.conv }}")
        hand_option: $([ -n "${{ matrix.hand }}" ] && printf " -e HAND=${{ matrix.hand }}")
        hand_suffix: $([ -n "${{ matrix.hand }}" ] && printf "_${{ matrix.hand }}")
      run: |
        set -x
        echo "::set-output name=build-args::${{ env.conv_option }}${{ env.hand_option }}"
        echo "::set-output name=file-name::${{ matrix.keyboard }}${{ env.branch_suffix }}${{ env.conv_suffix }}${{ env.hand_suffix }}"

    - name: Build ${{ matrix.keyboard }} firmware
      continue-on-error: true
      working-directory: users/${{ github.actor }}/keymaps
      run: qmk -v compile -j3 ${{ steps.vars.outputs.build-args }} ${{ matrix.keyboard }}.json

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 3
        name: ${{ steps.vars.outputs.file-name }}
        path: |
          *.hex
          *.bin
          *.uf2
