name: Development Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
        include:
        - keyboard: cradio
          branch: avr-dev
        - keyboard: cradio
          branch: convert-kb2040
# git remote add src https://github.com/qmk/qmk_firmware.git; git fetch src; git pull src pull/17514/head --no-edit

    steps:
    - name: Checkout ${{ matrix.branch }} branch
      uses: actions/checkout@v3
      with:
        repository: filterpaper/qmk_firmware
        ref: ${{ matrix.branch }}
        submodules: true

    - name: Checkout userspace
      uses: actions/checkout@v3
      with:
        path: users/${{ github.actor }}
        persist-credentials: false

    - name: Build ${{ matrix.keyboard }} firmware
      continue-on-error: true
      working-directory: users/${{ github.actor }}/keymaps
      env:
        build_option: $([ "${{ matrix.branch }}" = "convert-kb2040" ] && printf " -e CONVERT_TO=kb2040")
      run: qmk compile -j3 ${{ env.build_option }} ${{ matrix.keyboard }}.json

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        retention-days: 3
        name: development_${{ matrix.keyboard }}_${{ matrix.branch }}
        path: |
          *.hex
          *.bin
          *.uf2
