# workflow_pruner.yml
# This workflow prunes old workflow runs for an entire repository.
name: Workflow Run Pruner
on:
  schedule:
  - cron: '0 */12 * * *'
  workflow_dispatch:
  push:

jobs:
  prune:
    uses: filterpaper/workflows/.github/workflows/workflow_pruner.yml@main
